### PR TITLE
Fix for Clang not working with MacOS

### LINKED ISSUE #11: [BUG] Cannot use Clang on MacOS
**Describe the bug**

Attempting to use Clang as the toolchain compiler does not work on MacOS.

**Steps to Reproduce**

1. Create a simple test project
2. Use `dds build -t :clang`
3. Get error message

**`dds` Output**

```
Assertion failed: (false && "No archive suffix"), function operator(), file /Users/runner/runners/2.163.1/work/1/s/src/dds/toolchain/from_dds.cpp, line 512.

```

**Desktop (please complete the following information):**

 - Operating System: MacOS
 - Compiler: Clang
 - `dds` Version: `0.1.0-alpha.2`

**Additional context**

Using `dds build -t :gcc-9` works fine (using GCC provided by homebrew). Writing a custom toolchain file such as

```
Compiler-Id: Clang
C++-Compiler: clang++
```

produces the same error message as above.

### PR DESCRIPTION
**Pull request by tcbrindle**
This is intended to fix #11.

Unfortunately I haven't been able to successfully build DDS yet to actually try it out, but looking at the surrounding code it seems like the right solution...

### CODE REVIEW

**Comment by tcbrindle** [comment]
Having now successfully built DDS, the next problem was that even when `Compiler-ID` is `Clang`, DDS was still trying to link with `libstdc++fs`. This is probably correct on Linux, where libstdc++ is the default standard library, but fails on MacOS, where libc++ is used (and would also fail for Linux users who manually specified `-stdlib=libc++` in their compile flags).

With the second change, DDS can now successfully compile a simple test project on MacOS.

File: src/dds/toolchain/from_dds.cpp [hunk 1]
```diff
@@ -570,14 +570,21 @@ toolchain dds::parse_toolchain_dds(const lm::pair_list& pairs, strv context) {
...
         if (is_msvc) {
             ret = {get_compiler(language::cxx), "/nologo", "/EHsc", "<IN>", "/Fe<OUT>"};
-        } else if (is_gnu_like) {
+        } else if (is_gnu) {
             ret = {get_compiler(language::cxx),
                    "-fPIC",
                    "-fdiagnostics-color",
                    "<IN>",
                    "-pthread",
                    "-lstdc++fs",
```
Comment (vector-of-bool) [inline src/dds/toolchain/from_dds.cpp]: The `-lstdc++fs` is a bit of a goof that should be fixed in a separate context. I'm leaving this note for later.

**Comment by vector-of-bool** [comment]
Sorry for the delay (again). I'll merge this one and have a few tweaks for the `stdc++fs` work later.
